### ISSUE TITLE
Bib files missing

### ISSUE THREAD

**Issue by ccottap** [JJ/vizgec2016#1]
Cannot run bibtex, the .bib files are missing @JJ @mariosky

**Comment by JJ** [comment]
that is why y Inserted the .bbl. I''ll add them.

2016-04-03 13:46 GMT+02:00 Carlos Cotta notifications@github.com:

> Cannot run bibtex, the .bib files are missing @JJ https://github.com/JJ
> @mariosky https://github.com/mariosky
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/JJ/vizgec2016/issues/1

## 

JJ
